;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haskell-process-load-file
        julia-latexsub-or-indent
        markdown-cycle
        overwrite-mode
        xterm-paste
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-semi&comma
        c-indent-line-or-region
        compile
        markdown-outdent-or-delete
        ))
